stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:3.8.7-openjdk-17
  script:
    - mvn test
