stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn test

checkstyle-job:
  stage: test
  script:
    - mvn checkstyle:check
  allow_failure: true # Optional: macht den Job nicht-blockierend
  artifacts:
    paths:
      - target/checkstyle-result.xml

package:
  stage: package
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
