name: Publish to GitHub Packages

on:
  push:
    branches: [ "main" ] # oder dein Hauptbranch

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write   # wichtig für GitHub Packages
      contents: read    # notwendig für Checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Configure Maven to use GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml

      - name: Build and Deploy
        run: mvn clean deploy -DskipTests
